# Basic Operations on Quantum Objects

Following: http://qutip.org/docs/latest/guide/guide-basics.html

## First things first

In [1]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## The quantum object class

### Introduction

In [2]:
Qobj()

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]

In [3]:
Qobj([[1], [2], [3], [4], [5]])

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]

In [4]:
x = np.array([[1, 2, 3, 4, 5]])
Qobj(x)

Quantum object: dims = [[1], [5]], shape = (1, 5), type = bra
Qobj data =
[[1. 2. 3. 4. 5.]]

In [5]:
x = np.array([1, 2, 3, 4, 5])
Qobj(x)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]

In [6]:
r = np.random.rand(4, 4)
Qobj(r)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.97761091 0.51557508 0.25299093 0.06751306]
 [0.69682285 0.77729871 0.50075491 0.92264695]
 [0.67537744 0.58121472 0.37035759 0.08049168]
 [0.78605878 0.50183916 0.33570775 0.3686084 ]]

### States and operators

In [7]:
basis(2, 1)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [8]:
fock(2, 0)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [9]:
coherent(2, 1)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.54030231]
 [0.84147098]]

In [10]:
coherent_dm(2, 1)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.29192658 0.45464871]
 [0.45464871 0.70807342]]

In [11]:
thermal_dm(2, 1)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.66666667 0.        ]
 [0.         0.33333333]]

And many, many operators...

In [12]:
qeye(2)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In [13]:
num(2)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 1.]]

In [14]:
create(2)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0. 0.]
 [1. 0.]]

In [15]:
sigmax()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

Some more examples...

In [16]:
basis(5, 3)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]
 [0.]]

In [18]:
#basis(5, 5)
# ... error, as expected

In [19]:
coherent(5, 0.5 - 0.5j)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[ 0.7788017 +0.j        ]
 [ 0.38939142-0.38939142j]
 [ 0.        -0.27545895j]
 [-0.07898617-0.07898617j]
 [-0.04314271+0.j        ]]

In [20]:
destroy(4)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.        ]
 [0.         0.         1.41421356 0.        ]
 [0.         0.         0.         1.73205081]
 [0.         0.         0.         0.        ]]

In [21]:
jmat(5/2.0, '+')

Quantum object: dims = [[6], [6]], shape = (6, 6), type = oper, isherm = False
Qobj data =
[[0.         2.23606798 0.         0.         0.         0.        ]
 [0.         0.         2.82842712 0.         0.         0.        ]
 [0.         0.         0.         3.         0.         0.        ]
 [0.         0.         0.         0.         2.82842712 0.        ]
 [0.         0.         0.         0.         0.         2.23606798]
 [0.         0.         0.         0.         0.         0.        ]]

### Qobj attributes

In [22]:
q = destroy(4)
q.dims

[[4], [4]]

In [23]:
q.shape

(4, 4)

In [24]:
print(q)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.        ]
 [0.         0.         1.41421356 0.        ]
 [0.         0.         0.         1.73205081]
 [0.         0.         0.         0.        ]]


The `Qobj` class may be viewed as a container for the properties needed to characterize a quantum operator or state vector.

In [25]:
q.type

'oper'

In [26]:
q.isherm

False

In [27]:
q.data

<4x4 sparse matrix of type '<class 'numpy.complex128'>'
	with 3 stored elements in Compressed Sparse Row format>

### Qobj Math

In [28]:
q = destroy(4)
x = sigmax()

In [29]:
q + 5

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[5.         1.         0.         0.        ]
 [0.         5.         1.41421356 0.        ]
 [0.         0.         5.         1.73205081]
 [0.         0.         0.         5.        ]]

In [30]:
x * x

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In [31]:
q ** 3

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         2.44948974]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]

In [32]:
x / np.sqrt(2)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.         0.70710678]
 [0.70710678 0.        ]]

## Functions operating on Qobj class

In [33]:
q.check_herm()

False

In [34]:
q.conj()

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.        ]
 [0.         0.         1.41421356 0.        ]
 [0.         0.         0.         1.73205081]
 [0.         0.         0.         0.        ]]

In [35]:
q.dag()

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         0.        ]
 [1.         0.         0.         0.        ]
 [0.         1.41421356 0.         0.        ]
 [0.         0.         1.73205081 0.        ]]

In [36]:
q.tr()

0.0

And more examples...

In [37]:
basis(5, 3)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]
 [0.]]

In [38]:
basis(5, 3).dag()

Quantum object: dims = [[1], [5]], shape = (1, 5), type = bra
Qobj data =
[[0. 0. 0. 1. 0.]]

In [39]:
basis(5, 3).dag() * basis(5, 3)

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[1.]]

In [40]:
basis(5, 3) * basis(5, 3).dag()

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]

In [41]:
coherent_dm(5, 1)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.36791117 0.36774407 0.26105441 0.14620658 0.08826704]
 [0.36774407 0.36757705 0.26093584 0.14614018 0.08822695]
 [0.26105441 0.26093584 0.18523331 0.10374209 0.06263061]
 [0.14620658 0.14614018 0.10374209 0.05810197 0.035077  ]
 [0.08826704 0.08822695 0.06263061 0.035077   0.0211765 ]]

In [42]:
coherent_dm(5, 1).diag()

array([0.36791117, 0.36757705, 0.18523331, 0.05810197, 0.0211765 ])

In [43]:
coherent_dm(5, 1).full()

array([[0.36791117+0.j, 0.36774407+0.j, 0.26105441+0.j, 0.14620658+0.j,
        0.08826704+0.j],
       [0.36774407+0.j, 0.36757705+0.j, 0.26093584+0.j, 0.14614018+0.j,
        0.08822695+0.j],
       [0.26105441+0.j, 0.26093584+0.j, 0.18523331+0.j, 0.10374209+0.j,
        0.06263061+0.j],
       [0.14620658+0.j, 0.14614018+0.j, 0.10374209+0.j, 0.05810197+0.j,
        0.035077  +0.j],
       [0.08826704+0.j, 0.08822695+0.j, 0.06263061+0.j, 0.035077  +0.j,
        0.0211765 +0.j]])

In [44]:
coherent_dm(5, 1).norm()

1.0000000252077326

In [47]:
coherent_dm(5, 1).sqrtm()

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[0.36791119+0.00000000e+00j 0.36774406+0.00000000e+00j
  0.2610544 +0.00000000e+00j 0.14620658+0.00000000e+00j
  0.08826704+0.00000000e+00j]
 [0.36774406+0.00000000e+00j 0.36757705+4.23874181e-11j
  0.26093584+1.25558676e-10j 0.14614018-2.58178591e-10j
  0.08822695-1.20293587e-10j]
 [0.2610544 +0.00000000e+00j 0.26093584+1.25558676e-10j
  0.18523332+3.71925960e-10j 0.10374209-7.64768498e-10j
  0.06263061-3.56329879e-10j]
 [0.14620658+0.00000000e+00j 0.14614018-2.58178591e-10j
  0.10374209-7.64768498e-10j 0.05810197+1.57254647e-09j
  0.035077  +7.32699235e-10j]
 [0.08826704+0.00000000e+00j 0.08822695-1.20293587e-10j
  0.06263061-3.56329879e-10j 0.035077  +7.32699235e-10j
  0.0211765 +3.41387792e-10j]]

In [48]:
coherent_dm(5, 1).sqrtm().tidyup()

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[0.36791119+0.00000000e+00j 0.36774406+0.00000000e+00j
  0.2610544 +0.00000000e+00j 0.14620658+0.00000000e+00j
  0.08826704+0.00000000e+00j]
 [0.36774406+0.00000000e+00j 0.36757705+4.23874181e-11j
  0.26093584+1.25558676e-10j 0.14614018-2.58178591e-10j
  0.08822695-1.20293587e-10j]
 [0.2610544 +0.00000000e+00j 0.26093584+1.25558676e-10j
  0.18523332+3.71925960e-10j 0.10374209-7.64768498e-10j
  0.06263061-3.56329879e-10j]
 [0.14620658+0.00000000e+00j 0.14614018-2.58178591e-10j
  0.10374209-7.64768498e-10j 0.05810197+1.57254647e-09j
  0.035077  +7.32699235e-10j]
 [0.08826704+0.00000000e+00j 0.08822695-1.20293587e-10j
  0.06263061-3.56329879e-10j 0.035077  +7.32699235e-10j
  0.0211765 +3.41387792e-10j]]

In [49]:
basis(4, 1).unit()

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]

In [50]:
(basis(4, 2) + basis(4, 1)).unit()

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]]