# Manipulating States and Operators

Following: http://qutip.org/docs/latest/guide/guide-states.html

## Introduction

Fore more, see the [tutorials page](http://qutip.org/tutorials.html).

## State Vectors (kets or bras)

In [1]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
vac = basis(5, 0)
vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [3]:
a = destroy(5)
a

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.         0.        ]
 [0.         0.         1.41421356 0.         0.        ]
 [0.         0.         0.         1.73205081 0.        ]
 [0.         0.         0.         0.         2.        ]
 [0.         0.         0.         0.         0.        ]]

In [4]:
a * vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [5]:
a.dag() * vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]]

In [6]:
a.dag() * a.dag() * vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.        ]
 [0.        ]
 [1.41421356]
 [0.        ]
 [0.        ]]

In [7]:
c = create(5)
c

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         0.         0.        ]
 [1.         0.         0.         0.         0.        ]
 [0.         1.41421356 0.         0.         0.        ]
 [0.         0.         1.73205081 0.         0.        ]
 [0.         0.         0.         2.         0.        ]]

In [8]:
c * c * vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.        ]
 [0.        ]
 [1.41421356]
 [0.        ]
 [0.        ]]

In [9]:
c ** 2 * vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.        ]
 [0.        ]
 [1.41421356]
 [0.        ]
 [0.        ]]

In [10]:
c * a * vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [11]:
# c * a on the |1> state
c * a * (c * vac)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]]

In [12]:
# c * a on the |2> state
c * a * (c**2 * vac)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.        ]
 [0.        ]
 [2.82842712]
 [0.        ]
 [0.        ]]

In [13]:
# note that wasn't normalized properly...
c * a * (c**2 * vac).unit()

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [2.]
 [0.]
 [0.]]

In [14]:
ket = basis(5, 2)
ket

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]
 [0.]]

In [15]:
n = num(5)
n

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 4.]]

In [16]:
# instead of c * a * (c**2 * vac).unit(), have:
n * ket

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [2.]
 [0.]
 [0.]]

In [17]:
ket = (basis(5, 0) + basis(5, 1)).unit(); ket

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.70710678]
 [0.70710678]
 [0.        ]
 [0.        ]
 [0.        ]]

In [18]:
n * ket

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.        ]
 [0.70710678]
 [0.        ]
 [0.        ]
 [0.        ]]

In [19]:
# coherent and squeezed states
vac = basis(5, 0)
d = displace(5, 1j)
s = squeeze(5, 0.25 + 0.25j)

In [20]:
d * vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[ 0.60655682+0.j        ]
 [ 0.        +0.60628133j]
 [-0.4303874 +0.j        ]
 [ 0.        -0.24104351j]
 [ 0.14552147+0.j        ]]

In [21]:
d * s * vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[ 0.65893786+0.08139381j]
 [ 0.10779462+0.51579735j]
 [-0.37567217-0.01326853j]
 [-0.02688063-0.23828775j]
 [ 0.26352814+0.11512178j]]

## Density matrices

We want to explore the dynamics of **open** quantum systems, where the general state is no longer a state vector but rather a density matrix.

In [22]:
ket = basis(5, 2)
ket * ket.dag()

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

In [23]:
fock_dm(5, 2)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

In [24]:
ket2dm(ket)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

For a density matrix with equal classical probability of being found in $|2\rangle$ or $|4\rangle$:

In [25]:
0.5 * ket2dm(basis(5, 4)) + 0.5 * ket2dm(basis(5, 2))

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.5]]

In [26]:
# or...
0.5 * (fock_dm(5, 2) + fock_dm(5, 4))

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.5]]

We also have functions for coherent state and thermal state density matrices:

In [27]:
coherent_dm(5, 1.25)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.20980701 0.26141096 0.23509686 0.15572585 0.13390765]
 [0.26141096 0.32570738 0.29292109 0.19402805 0.16684347]
 [0.23509686 0.29292109 0.26343512 0.17449684 0.1500487 ]
 [0.15572585 0.19402805 0.17449684 0.11558499 0.09939079]
 [0.13390765 0.16684347 0.1500487  0.09939079 0.0854655 ]]

In [28]:
thermal_dm(5, 1.25)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.46927974 0.         0.         0.         0.        ]
 [0.         0.26071096 0.         0.         0.        ]
 [0.         0.         0.14483942 0.         0.        ]
 [0.         0.         0.         0.08046635 0.        ]
 [0.         0.         0.         0.         0.04470353]]

A coherent state is the specific quantum state of the quantum harmonic oscillator with dynamics most closely resembling a classical harmonic oscillator.

A single mode thermal coherent state is produced by displacing a thermal mixed state in phase space -- analogous to the displacement of the vacuum state in view of generating a coherent state.

Useful utility functions:

In [29]:
x = coherent_dm(5, 1.25)
y = coherent_dm(5, 1.25j)
z = thermal_dm(5, 0.125)

In [30]:
fidelity(x, x)

1.0000000069648771

In [31]:
tracedist(y, y)

0.0

In [32]:
hellinger_dist(y, y)

0.0

For pure states, the trace distance and the fidelity distance are related by $T = \sqrt{1 - F^2}$, and the quantum Hellinger distance (QHE) is $\sqrt{2 - 2 |\langle \psi | \phi \rangle|^2}$.

In [33]:
tracedist(y, x)

0.9771565905440509

In [34]:
np.sqrt(1 - fidelity(y, x)**2)

0.9771565701294492

For a pure and a mixed state, $1 - F^2 \leq T$.

In [35]:
1 - fidelity(x, z) ** 2

0.778289051041259

In [36]:
tracedist(x, z)

0.8559028328862543

## Qubit (two-level) systems

We use the same `basis` and `fock` functions with only two levels:

In [37]:
spin = basis(2, 0)

In [38]:
vac = basis(2, 0)

At this point there is no difference - the differences comes from the action of the spin operators.

In [39]:
vac

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [40]:
c = create(2)
c * vac

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [41]:
spin

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [42]:
sigmap() * spin

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [0.]]

The `sigmap` operator acting on a spin state returns the `basis(2, 0)` to the zero vector. To see why:

In [43]:
sigmaz()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [44]:
sigmaz() * spin

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [45]:
spin2 = basis(2, 1); spin2

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [46]:
sigmaz() * spin2

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[ 0.]
 [-1.]]

So, `sigmap() * spin` raises the qubit state out of the truncated two-level Hilbert space, resulting in the zero state.

To create spin operators for higher spin systems, the `qutip.operators.jmat` function is useful.

## Expectation values

In [47]:
vac = basis(5, 0)
one = basis(5, 1)
c = create(5)
N = num(5)

In [48]:
expect(N, vac)

0.0

In [49]:
expect(N, one)

1.0

In [50]:
coh = coherent_dm(5, 1.0j)

In [51]:
expect(N, coh)

0.9970555745806597

In [52]:
cat = (basis(5, 4) + 1.0j * basis(5, 3)).unit()

In [53]:
expect(c, cat)

0.9999999999999998j

The `qutip.expect` function also accepts lists or arrays of state vectors or density matrices for the second input.

In [54]:
states = [(c**k * vac).unit() for k in range(5)]

In [55]:
expect(N, states)

array([0., 1., 2., 3., 4.])

In [56]:
cat_list = [(basis(5, 4) + x * basis(5, 3)).unit()
            for x in [0, 1.0j, -1.0, -1.0j]]

In [57]:
expect(c, cat_list)

array([ 0.+0.j,  0.+1.j, -1.+0.j,  0.-1.j])

`qutip.expect` looks to see if the operator is Hermitian. If it is, the output will always be real, if not, it will be complex.

In [58]:
up = basis(2, 0)
down = basis(2, 1)

In [59]:
expect(sigmaz(), up)

1.0

In [60]:
expect(sigmaz(), down)

-1.0

In [61]:
sigmaz()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [62]:
spin1 = basis(2, 0)
spin2 = basis(2, 1)
two_spins = tensor(spin1, spin2); two_spins

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]

In [63]:
sz1 = tensor(sigmaz(), qeye(2)); sz1

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0. -1.]]

In [64]:
sz2 = tensor(qeye(2), sigmaz()); sz2

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]

In [65]:
expect(sz1, two_spins)

1.0

In [66]:
expect(sz2, two_spins)

-1.0

## Superoperators and Vectorized Operators